### PR TITLE
Improvements to Docker image

### PR DESCRIPTION
**Pull request by egli**
Here's a few improvements to the Docker image and the docker-compose file

### Docker image
1. Install the webui in a standard location inside the image

### Compose file
1. Use the image names from Docker hub, so that automatic pulling from hub works
2. Remove an environment variable which is set by default anyway
3. Add a volume for the pipeline data, so that old jobs aren't lost on restart

### CODE REVIEW

**Comment by bertfrees** [comment]
Looks good!

**Comment by egli** [comment]
@josteinaj what's up with this PR? Aren't you going to merge it?

**Comment by bertfrees** [comment]
Bump

**Comment by josteinaj** [comment]
Sorry, I completely missed this one. I'll have a look and merge.

**Comment by josteinaj** [comment]
It's merged now. Docker hub should start building the image automatically, but I don't know how fast it will pick it up. Hopefully soon.

**Pull request merged**
