### PR TITLE
Bugfixes in regex field validation

### PR DESCRIPTION
**Pull request by bertfrees**
- .attr("oninput", ...) and .attr("oninvalid", ...) did not work as expected. Replaced by .on("input", ...) and .on("invalid", ...).
- On "input" events the current value needs to be matched against the pattern.
- Escaping " to &quot; is not needed. This is done by the Scala template system.

Make a bugfix release of this change and merge with master afterwards.

### CODE REVIEW

**Comment by josteinaj** [comment]
Merged as 4ade2dccaf208da3e11d270dce325c24de0e2f7a in d801db3edf80752e1a28cf67a98b0b8b9dd066f9.

**Comment by bertfrees** [comment]
Yes, when you click release it's released after an hour or so. Is it done already? My intention was to not include the "type and data-type have been merged" commit, to only merge it again after the release had been made. The type/data-type merge depends on a newer version of the Pipeline and/or clientlib-java, so people won't be able to use 2.6.2 if they want regex validation :)

**Comment by bertfrees** [comment]
... but it's OK. I have created a "2.6.2-beta" Docker image from the fix-regex-validation branch which Ole can use.

**Comment by bertfrees** [comment]
Can I just fix the master branch? It's bugging me that it contains the same commits twice :)

**Comment by josteinaj** [comment]
> My intention was to not include the "type and data-type have been merged" commit

Oh, whoops. Sorry. I thought it was safe to release.

> ... but it's OK. I have created a "2.6.2-beta" Docker image from the fix-regex-validation branch which Ole can use.

Ok, good :).

> Can I just fix the master branch?

Yeah, fix the master branch if you want to. I didn't want to force push it in case it broke something, but the release commit and tag should be on the develop branch so it should be fine.

**Comment by bertfrees** [comment]
Hmm yeah, I guess we shouldn't force push to a master branch. OK, I'll just forget about it. It's my own fault for not using the develop branch.

**Pull request closed without merging**
