### PR TITLE
v2.3.0

### LINKED ISSUE #40: Hide messages in the execution log with the severity "DEBUG"
_From @josteinaj on January 26, 2015 13:28_

Make messages with "DEBUG" severity part of a nested list under the first preceding message that does not have the severity "DEBUG". The DEBUG messages would not be displayed at the top of the Web UI when running scripts, and the list they are in would be automatically collapsed when a new non-DEBUG message appears. These collapsed lists can be expanded manually by the user afterwards. The DEBUG messages could possibly have a lower priority for screen readerrs in the aria live region as well.

Only scripts (and the scripts main components) should have non-DEBUG messages from now on.

related issue: daisy/pipeline-issues#442

_Copied from original issue: daisy/pipeline-issues#443_

### LINKED ISSUE #61: In the job view; if the job is not found in the engine, give a friendly message saying so
Something along the lines of "the results have been deleted" + "please restart the job to get the results again".

### LINKED ISSUE #81: Cannot turn normal user into admin user
POST submits fine but somehow it's not stored in the DB it seems. Needs to be investigated.

### LINKED ISSUE #82: Option values in template details are not displayed correctly under "my templates"
...it works for "all templates" though.

### LINKED ISSUE #89: Implement progressbar
According to description here: daisy/pipeline-issues#445

### PR DESCRIPTION
**Pull request by josteinaj**
# v2.3.0

## Features
- Implement progressbar, closes #89

## Improvements
- Hide messages in the execution log that does not have severity "INFO", closes #40
- In the job view; if the job is not found in the engine, give a friendly message saying so, closes #61

## Bugfixes
- Option values in template details are now displayed correctly under "my templates", fixes #82
- Make it possible to turn normal user into admin user, fixes #81

### CODE REVIEW

**Comment by josteinaj** [comment]
@bertfrees Web UI v2.3.0 is now available on maven central. The main feature is the progressbar (since it's very visible). As no scripts are sending progress information yet the only testing I've done is with a bunch of unit tests in clientlib-java and some manual tests with scripts that send no progress info. The behavior when there's no progress info available is that it will take approximately a minute to fill up the progressbar, but the progress follows an inverse exponential curve so while it never stops moving, it never fully hits 100% either. The progressbar should in theory be accessible since it's got the appropriate aria attributes.

**Comment by bertfrees** [comment]
Already done? :open_mouth: Jostein, you're a pleasure to work with!

Only concern I have is that the progress bar might currently cause more problems than it will solve. I'm afraid the exponential curve will just confuse people. Maybe we should only show it as of the first progress message it receives?

**Comment by josteinaj** [comment]
I'm not sure if the progressbar with no progress info is less confusing than a progressbar with a littlebit of progress info. For instance, say I add to the NLB script NLB-preprocessing at 0-10 %, and the generic script at 10-100%, I don't think the estimation would be much better than with no progress info; it might even be worse if the preprocessing stuff isn't actually 10% of the process but maybe 1% or 40%. We just need to gradually add more and more progress info to the modules, and tune them as we go I think.

And we'll need to try out if XSLT- and Java-messages are available through the execution log.

**Comment by bertfrees** [comment]
Actually I meant show no progress bar at all until the first message arrives.

**Comment by josteinaj** [comment]
Ah, I see. Yeah I agree. Or maybe make it an "indeterminate" progress bar until the first message arrives?

**Comment by bertfrees** [comment]
Yes, something like that.

**Pull request merged**
