### PR TITLE
Add a Dockerfile

### PR DESCRIPTION
**Pull request by egli**
The Dockerfile employs a multistage build to build the webui and then install it in a separate image

I will add a docker compose file that illustrates how the pipeline and the webui can be connected to a running system.

Also I have a Dockerfile that creates an all-in-one solution using the debian images. I'll push that separately

### CODE REVIEW

**Comment by egli** [comment]
I rebased this PR onto develop

**Comment by bertfrees** [comment]
Depends on https://github.com/daisy/pipeline-assembly/pull/140

**Comment by bertfrees** [comment]
@josteinaj Seems Travis it is still configured for Maven.

**Comment by josteinaj** [comment]
@bertfrees yeah. The tests are in a bad condition though; I just test the Web UI manually. Making proper tests would require quite a bit of work, and I don't think it's currently worth the effort. Would it be ok to just delete the `.travis.yml` for now?

**Comment by bertfrees** [comment]
OK, what you prefer.

**Comment by josteinaj** [comment]
Closed by #118.

**Pull request closed without merging**
